# AWS CodeDeploy 의 설정
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

permissions: # CodeDeploy에서 EC2 서버로 넘겨준 파일들에 모두 ec2-user 권한 부여
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
#  AfterInstall:
#    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료합니다.
#      timeout: 60
#      runas: ec2-user
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user
#  ValidateService:
#    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인 합니다.
#      timeout: 60
#      runas: ec2-user